import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Brain, 
  FileText, 
  BarChart3, 
  Users, 
  CheckCircle, 
  Star,
  ArrowRight,
  Mic,
  Target,
  TrendingUp,
  Shield,
  Zap
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import heroImage from "@/assets/hero-interview.jpg";

const Index = () => {
  const navigate = useNavigate();
  const [activeFeature, setActiveFeature] = useState(0);

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Mock Interviews",
      description: "Practice with realistic, role-specific questions generated by advanced AI",
      color: "text-primary"
    },
    {
      icon: Mic,
      title: "Voice & Text Input", 
      description: "Answer questions naturally using voice or text with real-time feedback",
      color: "text-accent"
    },
    {
      icon: FileText,
      title: "Resume Analysis",
      description: "Get detailed insights and ATS optimization suggestions",
      color: "text-warning"
    },
    {
      icon: BarChart3,
      title: "Progress Tracking",
      description: "Monitor your improvement with detailed analytics and scoring",
      color: "text-primary"
    }
  ];

  const benefits = [
    { icon: Target, text: "Targeted preparation for specific job roles" },
    { icon: TrendingUp, text: "Real-time performance analysis and feedback" },
    { icon: Shield, text: "ATS-optimized resume recommendations" },
    { icon: Zap, text: "Instant AI-powered evaluation and tips" }
  ];

  const stats = [
    { value: "95%", label: "Success Rate", description: "Users who got interviews" },
    { value: "2.5x", label: "Interview Confidence", description: "Average improvement" },
    { value: "1000+", label: "Questions Database", description: "Across all industries" },
    { value: "24/7", label: "Available", description: "Practice anytime" }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-secondary to-background">
      {/* Navigation */}
      <nav className="border-b border-border/50 bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Brain className="h-8 w-8 text-primary" />
              <span className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
                Smart Interview Buddy
              </span>
            </div>
            <div className="hidden md:flex items-center gap-6">
              <Button variant="ghost" onClick={() => navigate("/interview")}>
                Mock Interview
              </Button>
              <Button variant="ghost" onClick={() => navigate("/resume")}>
                Resume Analyzer
              </Button>
              <Button variant="ghost" onClick={() => navigate("/dashboard")}>
                Dashboard
              </Button>
              <Button variant="hero">
                Get Started
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative py-20 px-6 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-hero opacity-10"></div>
        <div className="max-w-7xl mx-auto relative">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8 text-center lg:text-left">
              <Badge className="bg-primary/10 text-primary border-primary/20 animate-pulse-glow">
                🚀 AI-Powered Interview Preparation
              </Badge>
              
              <h1 className="text-4xl md:text-6xl font-bold leading-tight">
                Master Your Next
                <span className="bg-gradient-hero bg-clip-text text-transparent block">
                  Job Interview
                </span>
              </h1>
              
              <p className="text-lg md:text-xl text-muted-foreground leading-relaxed">
                Practice with AI-generated questions, get real-time feedback, and optimize your resume 
                for maximum impact. Land your dream job with confidence.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4">
                <Button 
                  variant="premium" 
                  size="lg" 
                  className="text-lg px-8 py-6 h-auto"
                  onClick={() => navigate("/interview")}
                >
                  <Brain className="mr-2 h-6 w-6" />
                  Start Mock Interview
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
                
                <Button 
                  variant="outline" 
                  size="lg" 
                  className="text-lg px-8 py-6 h-auto"
                  onClick={() => navigate("/resume")}
                >
                  <FileText className="mr-2 h-5 w-5" />
                  Analyze Resume
                </Button>
              </div>
            </div>
            
            <div className="animate-float">
              <img 
                src={heroImage} 
                alt="AI-powered interview preparation" 
                className="rounded-2xl shadow-glow w-full max-w-lg mx-auto lg:max-w-none"
              />
            </div>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mt-16">
            {stats.map((stat, index) => (
              <div key={index} className="text-center space-y-2 animate-slide-in" style={{animationDelay: `${index * 0.1}s`}}>
                <div className="text-3xl md:text-4xl font-bold text-primary">{stat.value}</div>
                <div className="font-medium">{stat.label}</div>
                <div className="text-sm text-muted-foreground">{stat.description}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-4xl md:text-5xl font-bold">
              Comprehensive Interview
              <span className="bg-gradient-primary bg-clip-text text-transparent"> Preparation</span>
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Everything you need to excel in your job interviews, powered by advanced AI
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature, index) => (
              <Card 
                key={index}
                className="bg-gradient-card border-0 shadow-card-custom hover:shadow-elegant transition-all duration-300 cursor-pointer group"
                onMouseEnter={() => setActiveFeature(index)}
              >
                <CardHeader className="text-center">
                  <feature.icon className={`h-12 w-12 mx-auto mb-4 ${feature.color} group-hover:scale-110 transition-transform duration-300`} />
                  <CardTitle className="text-xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-center leading-relaxed">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20 px-6 bg-gradient-to-r from-primary/5 to-accent/5">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <div className="space-y-4">
                <Badge className="bg-accent/10 text-accent border-accent/20">
                  ✨ Why Choose Smart Interview Buddy
                </Badge>
                <h2 className="text-4xl font-bold leading-tight">
                  Prepare Smarter,
                  <span className="bg-gradient-success bg-clip-text text-transparent"> Interview Better</span>
                </h2>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  Our AI-powered platform adapts to your industry, experience level, and target role 
                  to provide personalized interview preparation that actually works.
                </p>
              </div>
              
              <div className="space-y-4">
                {benefits.map((benefit, index) => (
                  <div key={index} className="flex items-center gap-4 p-4 bg-background/50 rounded-lg border border-border/50">
                    <benefit.icon className="h-6 w-6 text-primary flex-shrink-0" />
                    <span className="font-medium">{benefit.text}</span>
                  </div>
                ))}
              </div>
              
              <Button 
                variant="success" 
                size="lg"
                onClick={() => navigate("/dashboard")}
              >
                <BarChart3 className="mr-2 h-5 w-5" />
                View Dashboard
              </Button>
            </div>
            
            <div className="space-y-6">
              <Card className="bg-gradient-primary border-0 shadow-glow text-primary-foreground animate-float">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Star className="h-5 w-5" />
                    AI-Powered Questions
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="mb-4">Get industry-specific questions tailored to your role:</p>
                  <ul className="space-y-2 text-sm opacity-90">
                    <li className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4" />
                      Technical challenges for developers
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4" />
                      Behavioral scenarios for managers
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="h-4 w-4" />
                      Case studies for consultants
                    </li>
                  </ul>
                </CardContent>
              </Card>
              
              <Card className="bg-gradient-success border-0 shadow-elegant text-accent-foreground">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <TrendingUp className="h-5 w-5" />
                    Real-time Feedback
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm opacity-90">
                    Get instant analysis on your answers including sentiment, keywords, 
                    and improvement suggestions to help you perform better.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <h2 className="text-4xl md:text-5xl font-bold">
            Ready to Ace Your
            <span className="bg-gradient-hero bg-clip-text text-transparent"> Interview?</span>
          </h2>
          <p className="text-xl text-muted-foreground leading-relaxed">
            Join thousands of successful candidates who used Smart Interview Buddy 
            to land their dream jobs. Start your preparation today.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              variant="premium" 
              size="lg" 
              className="text-lg px-8 py-6 h-auto"
              onClick={() => navigate("/interview")}
            >
              <Brain className="mr-2 h-6 w-6" />
              Start Practicing Now
            </Button>
            <Button 
              variant="outline" 
              size="lg" 
              className="text-lg px-8 py-6 h-auto"
              onClick={() => navigate("/dashboard")}
            >
              <Users className="mr-2 h-5 w-5" />
              View Success Stories
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 bg-background/80 backdrop-blur-sm py-12 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Brain className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold bg-gradient-primary bg-clip-text text-transparent">
              Smart Interview Buddy
            </span>
          </div>
          <p className="text-muted-foreground">
            Empowering job seekers with AI-powered interview preparation
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
